#!/usr/bin/env bash

export POSTGRES_USER=psqluser
export POSTGRES_PASSWORD=shift4398953
export POSTGRES_DB=shift
export POSTGRES_HOST=db

export NGINX_CONF=shift.conf
export NGINX_HTTPS_PORT=4443
export NGINX_CERT_NAME=default

# ENV
export ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BORZOI="${ROOT}/borzoi"
export BORZOI_MOTD="=== Herro bby ==="

#### DOCKER ####
export SERVICES="db nginx node hugo webpack caldav"
export COMPOSE_PROJECT_NAME="shift"

# CALDAV
export CALDAV_DB=caldav
export CALDAV_PORT=8888

# BOOTSTRAP
source "${BORZOI}/borzoi.sh"
borzoi $@
