baseURL = "/"
languageCode = "en-us"
title = "shift website reboot"
theme = "hugo-theme-learn"

[params]
  editURL = "/admin/#/collections/"
  description = "Shift website reboot documents"
  disableAssetsBusting = true # netlify doesn't need that
  enableGitInfo = true


# JSON enables lunr.js search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]
